### ISSUE TITLE
links inside declarations on 100 theorems page are broken

### ISSUE THREAD

**Issue by robertylewis** [leanprover-community/leanprover-community.github.io#390] opened 2023-10-25 18:11 UTC
At https://leanprover-community.github.io/100.html we format and linkify each declaration using info from doc-gen. But it seems the format of this info has changed since mathlib3 and now has relative links, so these links are broken: e.g. `irrational_sqrt_2` links to https://leanprover-community.github.io/Mathlib/Data/Real/Irrational.html#irrational_sqrt_two 

We could add a `<base>` tag to this page (and check that none of the other links are relative), or find some other solution.

**Comment by PatrickMassot** [comment] 2023-11-29 03:23
I cannot reproduce that. Do you still see this issue?

**Comment by robertylewis** [comment] 2023-12-17 22:43
Yes, I still see this issue. If you click on `irrational_sqrt_two`, or `Irrational`, or `Real.sqrt`, ... in the statement of item 1, it takes you to a nonexistent page.

**Comment by PatrickMassot** [comment] 2023-12-18 22:25
Ok, it turns out it was left explicitly broken in #349 for some very mysterious reason since the fix was trivial. This is now fixed.

**Closed by PatrickMassot** 2023-12-18 22:25 UTC
